/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BrokerCategory = IDL.Variant({
  'backgroundCheck' : IDL.Null,
  'other' : IDL.Null,
  'marketing' : IDL.Null,
  'peopleSearch' : IDL.Null,
  'publicRecords' : IDL.Null,
  'financial' : IDL.Null,
});
export const DataBroker = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'optOutUrl' : IDL.Text,
  'category' : BrokerCategory,
});
export const ProgressStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const PrivacyScore = IDL.Record({
  'score' : IDL.Nat,
  'persona' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'privacyScore' : PrivacyScore,
  'progress' : ProgressStatus,
});
export const PlatformCategory = IDL.Variant({
  'media' : IDL.Null,
  'other' : IDL.Null,
  'dataAggregator' : IDL.Null,
  'searchEngine' : IDL.Null,
  'eCommerce' : IDL.Null,
  'socialMedia' : IDL.Null,
});
export const Platform = IDL.Record({
  'name' : IDL.Text,
  'removalGuideUrl' : IDL.Text,
  'description' : IDL.Text,
  'category' : PlatformCategory,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getBrokers' : IDL.Func([], [IDL.Vec(DataBroker)], ['query']),
  'getBrokersWithStatus' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(DataBroker, ProgressStatus))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlatforms' : IDL.Func([], [IDL.Vec(Platform)], ['query']),
  'getPlatformsWithStatus' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Platform, ProgressStatus))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BrokerCategory = IDL.Variant({
    'backgroundCheck' : IDL.Null,
    'other' : IDL.Null,
    'marketing' : IDL.Null,
    'peopleSearch' : IDL.Null,
    'publicRecords' : IDL.Null,
    'financial' : IDL.Null,
  });
  const DataBroker = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'optOutUrl' : IDL.Text,
    'category' : BrokerCategory,
  });
  const ProgressStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const PrivacyScore = IDL.Record({ 'score' : IDL.Nat, 'persona' : IDL.Text });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'privacyScore' : PrivacyScore,
    'progress' : ProgressStatus,
  });
  const PlatformCategory = IDL.Variant({
    'media' : IDL.Null,
    'other' : IDL.Null,
    'dataAggregator' : IDL.Null,
    'searchEngine' : IDL.Null,
    'eCommerce' : IDL.Null,
    'socialMedia' : IDL.Null,
  });
  const Platform = IDL.Record({
    'name' : IDL.Text,
    'removalGuideUrl' : IDL.Text,
    'description' : IDL.Text,
    'category' : PlatformCategory,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getBrokers' : IDL.Func([], [IDL.Vec(DataBroker)], ['query']),
    'getBrokersWithStatus' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(DataBroker, ProgressStatus))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlatforms' : IDL.Func([], [IDL.Vec(Platform)], ['query']),
    'getPlatformsWithStatus' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Platform, ProgressStatus))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };