/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BrokerCategory = { 'backgroundCheck' : null } |
  { 'other' : null } |
  { 'marketing' : null } |
  { 'peopleSearch' : null } |
  { 'publicRecords' : null } |
  { 'financial' : null };
export interface DataBroker {
  'name' : string,
  'description' : string,
  'optOutUrl' : string,
  'category' : BrokerCategory,
}
export interface Platform {
  'name' : string,
  'removalGuideUrl' : string,
  'description' : string,
  'category' : PlatformCategory,
}
export type PlatformCategory = { 'media' : null } |
  { 'other' : null } |
  { 'dataAggregator' : null } |
  { 'searchEngine' : null } |
  { 'eCommerce' : null } |
  { 'socialMedia' : null };
export interface PrivacyScore { 'score' : bigint, 'persona' : string }
export type ProgressStatus = { 'notStarted' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface UserProfile {
  'id' : Principal,
  'privacyScore' : PrivacyScore,
  'progress' : ProgressStatus,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getBrokers' : ActorMethod<[], Array<DataBroker>>,
  'getBrokersWithStatus' : ActorMethod<[], Array<[DataBroker, ProgressStatus]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPlatforms' : ActorMethod<[], Array<Platform>>,
  'getPlatformsWithStatus' : ActorMethod<[], Array<[Platform, ProgressStatus]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];